mkdir -p .github/workflows
cat > .github/workflows/deploy.yml <<'YML'
# (paste workflow content here)
YML

git add .github/workflows/deploy.yml
git commit -m "Add GitHub Actions workflow: build & deploy to GitHub Pages"
git push origin main
